using ReactRedux.Common.Extensions;
using ReactRedux.DAL.Entities;
using ReactRedux.DAL.Entities.Catalogs;
using ReactRedux.DAL.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;

namespace ReactRedux.DAL
{
    public static class ReactReduxSeed
    {
        public static IEnumerable<T> GetSeedData<T>()
        {
            PropertyInfo property = typeof(ReactReduxSeed).GetProperties(BindingFlags.Static | BindingFlags.NonPublic)
                .SingleOrDefault(x => x.PropertyType == typeof(IEnumerable<T>));
            if (property == null)
            {
                throw new InvalidOperationException($"Cannot find seed data for type {typeof(T).Name}");
            }

            var seedData = (IEnumerable<T>)property.GetValue(null);
            if (typeof(T).IsSubclassOfRawGeneric(typeof(HistoryEntity<>)))
            {
                var authorProperty = typeof(T).GetProperty(nameof(HistoryEntity<object>.Author),
                    BindingFlags.Instance | BindingFlags.Public);
                foreach (T item in seedData)
                {
                    authorProperty.SetValue(item, "Developer");
                }
            }

            return seedData;
        }

        private static IEnumerable<FederalDistrict> FederalDistricts => new[]
        {
            new FederalDistrict{Id = 1, Code = "01", Name = "Центральный"},
            new FederalDistrict{Id = 2, Code = "02", Name = "Северо-Западный"},
            new FederalDistrict{Id = 3, Code = "03", Name = "Южный"},
            new FederalDistrict{Id = 4, Code = "04", Name = "Северо-Кавказский"},
            new FederalDistrict{Id = 5, Code = "05", Name = "Приволжский"},
            new FederalDistrict{Id = 6, Code = "06", Name = "Уральский"},
            new FederalDistrict{Id = 7, Code = "07", Name = "Сибирский"},
            new FederalDistrict{Id = 8, Code = "08", Name = "Дальневосточный"},
        };

        private static IEnumerable<Region> Regions => new[]
        {
                new Region{ Id =  1, Code = "01", Name = "Республика Адыгея", FederalDistrictId = 3 },
                new Region{ Id =  2, Code = "02", Name = "Республика Башкортостан", FederalDistrictId = 5 },
                new Region{ Id =  3, Code = "03", Name = "Республика Бурятия", FederalDistrictId = 8 },
                new Region{ Id =  4, Code = "04", Name = "Республика Алтай", FederalDistrictId = 7 },
                new Region{ Id =  5, Code = "05", Name = "Республика Дагестан", FederalDistrictId = 4 },
                new Region{ Id =  6, Code = "06", Name = "Республика Ингушетия", FederalDistrictId = 4 },
                new Region{ Id =  7, Code = "07", Name = "Кабардино-Балкарская Республика", FederalDistrictId = 4 },
                new Region{ Id =  8, Code = "08", Name = "Республика Калмыкия", FederalDistrictId = 3 },
                new Region{ Id =  9, Code = "09", Name = "Карачаево-Черкесская Республика", FederalDistrictId = 4 },
                new Region{ Id = 10, Code = "10", Name = "Республика Карелия", FederalDistrictId = 2 },
                new Region{ Id = 11, Code = "11", Name = "Республика Коми", FederalDistrictId = 2 },
                new Region{ Id = 12, Code = "12", Name = "Республика Марий Эл", FederalDistrictId = 5 },
                new Region{ Id = 13, Code = "13", Name = "Республика Мордовия", FederalDistrictId = 5 },
                new Region{ Id = 14, Code = "14", Name = "Республика Саха (Якутия)", FederalDistrictId = 8 },
                new Region{ Id = 15, Code = "15", Name = "Республика Северная Осетия - Алания", FederalDistrictId = 4 },
                new Region{ Id = 16, Code = "16", Name = "Республика Татарстан (Татарстан)", FederalDistrictId = 5 },
                new Region{ Id = 17, Code = "17", Name = "Республика Тыва", FederalDistrictId = 7 },
                new Region{ Id = 18, Code = "18", Name = "Удмуртская Республика", FederalDistrictId = 5 },
                new Region{ Id = 19, Code = "19", Name = "Республика Хакасия", FederalDistrictId = 7 },
                new Region{ Id = 20, Code = "20", Name = "Чеченская Республика", FederalDistrictId = 4 },
                new Region{ Id = 21, Code = "21", Name = "Чувашская Республика - Чувашия", FederalDistrictId = 5 },
                new Region{ Id = 22, Code = "22", Name = "Алтайский край", FederalDistrictId = 7 },
                new Region{ Id = 23, Code = "23", Name = "Краснодарский край", FederalDistrictId = 3 },
                new Region{ Id = 24, Code = "24", Name = "Красноярский край", FederalDistrictId = 7 },
                new Region{ Id = 25, Code = "25", Name = "Приморский край", FederalDistrictId = 8 },
                new Region{ Id = 26, Code = "26", Name = "Ставропольский край", FederalDistrictId = 4 },
                new Region{ Id = 27, Code = "27", Name = "Хабаровский край", FederalDistrictId = 8 },
                new Region{ Id = 28, Code = "28", Name = "Амурская область", FederalDistrictId = 8 },
                new Region{ Id = 29, Code = "29", Name = "Архангельская область", FederalDistrictId = 2 },
                new Region{ Id = 30, Code = "30", Name = "Астраханская область", FederalDistrictId = 3 },
                new Region{ Id = 31, Code = "31", Name = "Белгородская область", FederalDistrictId = 1 },
                new Region{ Id = 32, Code = "32", Name = "Брянская область", FederalDistrictId = 1 },
                new Region{ Id = 33, Code = "33", Name = "Владимирская область", FederalDistrictId = 1 },
                new Region{ Id = 34, Code = "34", Name = "Волгоградская область", FederalDistrictId = 3 },
                new Region{ Id = 35, Code = "35", Name = "Вологодская область", FederalDistrictId = 2 },
                new Region{ Id = 36, Code = "36", Name = "Воронежская область", FederalDistrictId = 1 },
                new Region{ Id = 37, Code = "37", Name = "Ивановская область", FederalDistrictId = 1 },
                new Region{ Id = 38, Code = "38", Name = "Иркутская область", FederalDistrictId = 7 },
                new Region{ Id = 39, Code = "39", Name = "Калининградская область", FederalDistrictId = 2 },
                new Region{ Id = 40, Code = "40", Name = "Калужская область", FederalDistrictId = 1 },
                new Region{ Id = 41, Code = "41", Name = "Камчатский край", FederalDistrictId = 8 },
                new Region{ Id = 42, Code = "42", Name = "Кемеровская область", FederalDistrictId = 7 },
                new Region{ Id = 43, Code = "43", Name = "Кировская область", FederalDistrictId = 5 },
                new Region{ Id = 44, Code = "44", Name = "Костромская область", FederalDistrictId = 1 },
                new Region{ Id = 45, Code = "45", Name = "Курганская область", FederalDistrictId = 6 },
                new Region{ Id = 46, Code = "46", Name = "Курская область", FederalDistrictId = 1 },
                new Region{ Id = 47, Code = "47", Name = "Ленинградская область", FederalDistrictId = 2 },
                new Region{ Id = 48, Code = "48", Name = "Липецкая область", FederalDistrictId = 1 },
                new Region{ Id = 49, Code = "49", Name = "Магаданская область", FederalDistrictId = 8 },
                new Region{ Id = 50, Code = "50", Name = "Московская область", FederalDistrictId = 1 },
                new Region{ Id = 51, Code = "51", Name = "Мурманская область", FederalDistrictId = 2 },
                new Region{ Id = 52, Code = "52", Name = "Нижегородская область", FederalDistrictId = 5 },
                new Region{ Id = 53, Code = "53", Name = "Новгородская область", FederalDistrictId = 2 },
                new Region{ Id = 54, Code = "54", Name = "Новосибирская область", FederalDistrictId = 7 },
                new Region{ Id = 55, Code = "55", Name = "Омская область", FederalDistrictId = 7 },
                new Region{ Id = 56, Code = "56", Name = "Оренбургская область", FederalDistrictId = 5 },
                new Region{ Id = 57, Code = "57", Name = "Орловская область", FederalDistrictId = 1 },
                new Region{ Id = 58, Code = "58", Name = "Пензенская область", FederalDistrictId = 5 },
                new Region{ Id = 59, Code = "59", Name = "Пермский край", FederalDistrictId = 5 },
                new Region{ Id = 60, Code = "60", Name = "Псковская область", FederalDistrictId = 2 },
                new Region{ Id = 61, Code = "61", Name = "Ростовская область", FederalDistrictId = 3 },
                new Region{ Id = 62, Code = "62", Name = "Рязанская область", FederalDistrictId = 1 },
                new Region{ Id = 63, Code = "63", Name = "Самарская область", FederalDistrictId = 5 },
                new Region{ Id = 64, Code = "64", Name = "Саратовская область", FederalDistrictId = 5 },
                new Region{ Id = 65, Code = "65", Name = "Сахалинская область", FederalDistrictId = 8 },
                new Region{ Id = 66, Code = "66", Name = "Свердловская область", FederalDistrictId = 6 },
                new Region{ Id = 67, Code = "67", Name = "Смоленская область", FederalDistrictId = 1 },
                new Region{ Id = 68, Code = "68", Name = "Тамбовская область", FederalDistrictId = 1 },
                new Region{ Id = 69, Code = "69", Name = "Тверская область", FederalDistrictId = 1 },
                new Region{ Id = 70, Code = "70", Name = "Томская область", FederalDistrictId = 7 },
                new Region{ Id = 71, Code = "71", Name = "Тульская область", FederalDistrictId = 1 },
                new Region{ Id = 72, Code = "72", Name = "Тюменская область", FederalDistrictId = 6 },
                new Region{ Id = 73, Code = "73", Name = "Ульяновская область", FederalDistrictId = 5 },
                new Region{ Id = 74, Code = "74", Name = "Челябинская область", FederalDistrictId = 6 },
                new Region{ Id = 75, Code = "75", Name = "Забайкальский край", FederalDistrictId = 8 },
                new Region{ Id = 76, Code = "76", Name = "Ярославская область", FederalDistrictId = 1 },
                new Region{ Id = 77, Code = "77", Name = "Москва", FederalDistrictId = 1 },
                new Region{ Id = 78, Code = "78", Name = "Санкт-Петербург", FederalDistrictId = 2 },
                new Region{ Id = 79, Code = "79", Name = "Еврейская автономная область", FederalDistrictId = 8 },
                new Region{ Id = 83, Code = "83", Name = "Ненецкий автономный округ", FederalDistrictId = 2 },
                new Region{ Id = 86, Code = "86", Name = "Ханты-Мансийский автономный округ - Югра", FederalDistrictId = 6 },
                new Region{ Id = 87, Code = "87", Name = "Чукотский автономный округ", FederalDistrictId = 8 },
                new Region{ Id = 89, Code = "89", Name = "Ямало-Ненецкий автономный округ", FederalDistrictId = 6 },
                new Region{ Id = 91, Code = "91", Name = "Республика Крым", FederalDistrictId = 3 },
                new Region{ Id = 92, Code = "92", Name = "Севастополь", FederalDistrictId = 3 },
        };

        //http://www.consultant.ru/document/cons_doc_LAW_60879/fbbc2fbe3a4087853c1b520d26c8fd06e73cde09/
        private static IEnumerable<IdentityDocument> IdentityDocuments => new[]
        {
            new IdentityDocument{Id = 1, Code = "21", Name = "Паспорт", NumberFormat = "99 99 9999999", NumberRegex = @"\d{2} ?\d{2} \d{6,7}"},
            new IdentityDocument{Id = 2, Code = "22", Name = "Загранпаспорт", NumberFormat = "99 9999999", NumberRegex = @"\d{2} \d{7}"},
            new IdentityDocument{Id = 3, Code = "27", Name = "Военный билет", NumberFormat = "бб 9999999", NumberRegex = @"[А-Я]{2} \d{6,7}"},
            new IdentityDocument{Id = 4, Code = "04", Name = "Удостоверение личности офицера", NumberFormat = "бб 9999999", NumberRegex = @"[А-Я]{2} \d{6,7}"},
            new IdentityDocument{Id = 5, Code = "24", Name = "Удостоверение личности военнослужащего Российской Федерации", NumberFormat = "бб 9999999", NumberRegex = @"[А-Я]{2} \d{7}"},
            new IdentityDocument{Id = 6, Code = "26", Name = "Паспорт моряка", NumberFormat = "бб 9999999", NumberRegex = @"[А-Я]{2} \d{6,7}"},
        };

        private static IEnumerable<EducationLevel> EducationalLevels => new[]
        {
            new EducationLevel{Id = 1, Code = "01", Name = "Среднее профессиональное"},
            new EducationLevel{Id = 2, Code = "02", Name = "Незаконченное высшее"},
            new EducationLevel{Id = 3, Code = "03", Name = "Высшее, бакалавриат"},
            new EducationLevel{Id = 4, Code = "04", Name = "Высшее, специалитет, магистратура"},
            new EducationLevel{Id = 5, Code = "05", Name = "Высшее образование и MBA"},
            new EducationLevel{Id = 6, Code = "06", Name = "Два и более высших образований"},
            new EducationLevel{Id = 7, Code = "07", Name = "Кандидат наук"},
            new EducationLevel{Id = 8, Code = "08", Name = "Доктор наук"},
        };

        private static IEnumerable<Industry> Industries => new[]
        {
            new Industry{Id =  1, Code = "01", Name = "Авиастроение"},
            new Industry{Id =  2, Code = "02", Name = "Автомобилестроение"},
            new Industry{Id =  3, Code = "03", Name = "Банки и страхование"},
            new Industry{Id =  4, Code = "04", Name = "Безопасность и охрана"},
            new Industry{Id =  5, Code = "05", Name = "Военная служба"},
            new Industry{Id =  6, Code = "06", Name = "Государственная служба"},
            new Industry{Id =  7, Code = "07", Name = "Гражданская авиация"},
            new Industry{Id =  8, Code = "08", Name = "Гражданская служба"},
            new Industry{Id =  9, Code = "09", Name = "Добыча полезных ископаемых"},
            new Industry{Id = 10, Code = "10", Name = "Здравоохранение"},
            new Industry{Id = 11, Code = "11", Name = "ЖКХ, Муниципальные учреждения"},
            new Industry{Id = 12, Code = "12", Name = "Издательская деятельность и СМИ"},
            new Industry{Id = 13, Code = "13", Name = "Информационные технологии"},
            new Industry{Id = 14, Code = "14", Name = "Искусство, культура и развлечения"},
            new Industry{Id = 15, Code = "15", Name = "Кино, радио и телевидение"},
            new Industry{Id = 16, Code = "16", Name = "Консалтинг"},
            new Industry{Id = 17, Code = "17", Name = "Лесозаготовка и производство изделий из дерева"},
            new Industry{Id = 18, Code = "18", Name = "Машиностроение"},
            new Industry{Id = 19, Code = "19", Name = "Металлургия"},
            new Industry{Id = 20, Code = "20", Name = "Научные исследования и разработки"},
            new Industry{Id = 21, Code = "21", Name = "Недвижимость"},
            new Industry{Id = 22, Code = "22", Name = "Нефтехимическая промышленность"},
            new Industry{Id = 23, Code = "23", Name = "Нефтепереработка, добыча"},
            new Industry{Id = 24, Code = "24", Name = "Образование"},
            new Industry{Id = 25, Code = "25", Name = "Обслуживание населения"},
            new Industry{Id = 26, Code = "26", Name = "Общественные организации и профсоюзы"},
            new Industry{Id = 27, Code = "27", Name = "Оптовая торговля"},
            new Industry{Id = 28, Code = "28", Name = "Переработка сырья и вторсырья"},
            new Industry{Id = 29, Code = "29", Name = "Пищевая промышленность"},
            new Industry{Id = 30, Code = "30", Name = "Работа с персоналом"},
            new Industry{Id = 31, Code = "31", Name = "Реклама и маркетинг"},
            new Industry{Id = 32, Code = "32", Name = "Религиозные организации"},
            new Industry{Id = 33, Code = "33", Name = "Рестораны и заведения общественного питания"},
            new Industry{Id = 34, Code = "34", Name = "Ритейл"},
            new Industry{Id = 35, Code = "35", Name = "Сельское хозяйство"},
            new Industry{Id = 36, Code = "36", Name = "Спорт и отдых"},
            new Industry{Id = 37, Code = "37", Name = "Строительство"},
            new Industry{Id = 38, Code = "38", Name = "Судостроение"},
            new Industry{Id = 39, Code = "39", Name = "Телекоммуникации и связь"},
            new Industry{Id = 40, Code = "40", Name = "Товары повседневного спроса"},
            new Industry{Id = 41, Code = "41", Name = "Транспорт и логистика"},
            new Industry{Id = 42, Code = "42", Name = "Туризм и гостиничный бизнес"},
            new Industry{Id = 43, Code = "43", Name = "Фармацевтика"},
            new Industry{Id = 44, Code = "44", Name = "Финансы и инвестиции"},
            new Industry{Id = 45, Code = "45", Name = "Электроника и электротехника"},
            new Industry{Id = 46, Code = "46", Name = "Энергетика"},
            new Industry{Id = 47, Code = "47", Name = "Химическая промышленность"},
            new Industry{Id = 48, Code = "48", Name = "Экология"},
            new Industry{Id = 49, Code = "49", Name = "Юридические услуги"},
        };

        private static IEnumerable<WorkArea> WorkAreas => new[]
        {
            new WorkArea{Id =  1, Code = "01", Name = "Административно-хозяйственное направление"},
            new WorkArea{Id =  2, Code = "02", Name = "Аналитика и исследования"},
            new WorkArea{Id =  3, Code = "03", Name = "Аудит"},
            new WorkArea{Id =  4, Code = "04", Name = "Безопасность"},
            new WorkArea{Id =  5, Code = "05", Name = "Высшее руководство"},
            new WorkArea{Id =  6, Code = "06", Name = "Делопроизводство"},
            new WorkArea{Id =  7, Code = "07", Name = "IT"},
            new WorkArea{Id =  8, Code = "08", Name = "Логистика"},
            new WorkArea{Id =  9, Code = "09", Name = "Маркетинг"},
            new WorkArea{Id = 10, Code = "10", Name = "Обучение"},
            new WorkArea{Id = 11, Code = "11", Name = "Отношения с органами власти"},
            new WorkArea{Id = 12, Code = "12", Name = "Охрана труда"},
            new WorkArea{Id = 13, Code = "13", Name = "Продажи"},
            new WorkArea{Id = 14, Code = "14", Name = "Производство"},
            new WorkArea{Id = 15, Code = "15", Name = "Связи с общественностью"},
            new WorkArea{Id = 16, Code = "16", Name = "Снабжение и закупки"},
            new WorkArea{Id = 17, Code = "17", Name = "Стратегический менеджмент"},
            new WorkArea{Id = 18, Code = "18", Name = "Управление проектами"},
            new WorkArea{Id = 19, Code = "19", Name = "Управление рисками"},
            new WorkArea{Id = 20, Code = "20", Name = "Управления персоналом"},
            new WorkArea{Id = 21, Code = "21", Name = "Финансы"},
            new WorkArea{Id = 22, Code = "22", Name = "Юриспруденция"},
        };

        private static IEnumerable<ManagementLevel> ManagementLevels => new[]
        {
            new ManagementLevel{Id = 1, Code = "01", Name = "Акционер/собственник"},
            new ManagementLevel{Id = 2, Code = "02", Name = "Член правления"},
            new ManagementLevel{Id = 3, Code = "03", Name = "Глава организации"},
            new ManagementLevel{Id = 4, Code = "04", Name = "Руководство высшего звена"},
            new ManagementLevel{Id = 5, Code = "05", Name = "Руководство среднего звена"},
            new ManagementLevel{Id = 6, Code = "06", Name = "Линейное/функциональное руководство"},
            new ManagementLevel{Id = 7, Code = "07", Name = "Ведущий специалист"},
        };

        private static IEnumerable<ManagementExperience> ManagementExperiences => new[]
        {
            new ManagementExperience{Id = 1, Code = "01", Name = "Менее 2 лет"},
            new ManagementExperience{Id = 2, Code = "02", Name = "От 2 до 5 лет"},
            new ManagementExperience{Id = 3, Code = "03", Name = "От 5 до 10 лет"},
            new ManagementExperience{Id = 4, Code = "04", Name = "10 лет и более"},
        };

        private static IEnumerable<EmployeesNumber> EmployeesNumbers => new[]
        {
            new EmployeesNumber{Id = 1, Code = "01", Name = "До 10"},
            new EmployeesNumber{Id = 2, Code = "02", Name = "От 11 до 50"},
            new EmployeesNumber{Id = 3, Code = "03", Name = "От 51 до 100"},
            new EmployeesNumber{Id = 4, Code = "04", Name = "От 101 до 500"},
            new EmployeesNumber{Id = 5, Code = "05", Name = "От 501 до 1000"},
            new EmployeesNumber{Id = 6, Code = "06", Name = "Свыше 1000"},
        };

        private static IEnumerable<Language> Languages => new[]
        {
            new Language{Id =  1, Code =         "abk", Name = "Абхазский"},
            new Language{Id =  2, Code =         "aze", Name = "Азербайджанский"},
            new Language{Id =  3, Code =         "sqi", Name = "Албанский"},
            new Language{Id =  4, Code =         "eng", Name = "Английский", Weight = 100},
            new Language{Id =  5, Code =         "ara", Name = "Арабский"},
            new Language{Id =  6, Code = "hye/axm/xcl", Name = "Армянский"},
            new Language{Id =  7, Code =         "aii", Name = "Ассирийский"},
            new Language{Id =  8, Code =         "afr", Name = "Африкаанс"},
            new Language{Id =  9, Code =         "ban", Name = "Балийский"},
            new Language{Id = 10, Code =         "eus", Name = "Баскский"},
            new Language{Id = 11, Code =         "bel", Name = "Белорусский"},
            new Language{Id = 12, Code =         "mya", Name = "Бирманский"},
            new Language{Id = 13, Code =         "bul", Name = "Болгарский"},
            new Language{Id = 14, Code =         "bos", Name = "Боснийский"},
            new Language{Id = 15, Code =         "bre", Name = "Бретонский"},
            new Language{Id = 16, Code =         "cym", Name = "Валлийский"},
            new Language{Id = 17, Code =         "hun", Name = "Венгерский"},
            new Language{Id = 18, Code =         "vie", Name = "Вьетнамский"},
            new Language{Id = 19, Code =         "haw", Name = "Гавайский"},
            new Language{Id = 20, Code =         "kal", Name = "Гренландский"},
            new Language{Id = 21, Code =         "ell", Name = "Греческий (новогреческий)"},
            new Language{Id = 22, Code =         "kat", Name = "Грузинский"},
            new Language{Id = 23, Code =         "dan", Name = "Датский"},
            new Language{Id = 24, Code =         "jrb", Name = "Еврейско-арабский"},
            new Language{Id = 25, Code =         "jpr", Name = "Еврейско-персидский"},
            new Language{Id = 26, Code =         "heb", Name = "Иврит"},
            new Language{Id = 27, Code =         "ind", Name = "Индонезийский"},
            new Language{Id = 28, Code =         "gle", Name = "Ирландский"},
            new Language{Id = 29, Code =         "isl", Name = "Исландский"},
            new Language{Id = 30, Code =         "spa", Name = "Испанский", Weight = 80},
            new Language{Id = 31, Code =         "ita", Name = "Итальянский", Weight = 80},
            new Language{Id = 32, Code =         "kaz", Name = "Казахский"},
            new Language{Id = 33, Code =         "cat", Name = "Каталанский"},
            new Language{Id = 34, Code =         "kir", Name = "Киргизский"},
            new Language{Id = 35, Code =         "zho", Name = "Китайский", Weight = 80},
            new Language{Id = 36, Code =         "kon", Name = "Конго"},
            new Language{Id = 37, Code =         "kor", Name = "Корейский"},
            new Language{Id = 38, Code =         "kur", Name = "Курдский"},
            new Language{Id = 39, Code =         "lao", Name = "Лаосский"},
            new Language{Id = 40, Code =         "lav", Name = "Латышский"},
            new Language{Id = 41, Code =         "lit", Name = "Литовский"},
            new Language{Id = 42, Code =         "ltz", Name = "Люксембургский"},
            new Language{Id = 43, Code =         "mad", Name = "Мадурский"},
            new Language{Id = 44, Code =         "mkd", Name = "Македонский"},
            new Language{Id = 45, Code =         "mlg", Name = "Малагасийский"},
            new Language{Id = 46, Code =         "msa", Name = "Малайский"},
            new Language{Id = 47, Code =         "mlt", Name = "Мальтийский"},
            new Language{Id = 48, Code =         "mah", Name = "Маршалльский"},
            new Language{Id = 49, Code =           "—", Name = "Молдавский"},
            new Language{Id = 50, Code =         "mon", Name = "Монгольский"},
            new Language{Id = 51, Code =         "deu", Name = "Немецкий", Weight = 90},
            new Language{Id = 52, Code =         "nep", Name = "Непальский"},
            new Language{Id = 53, Code =         "nld", Name = "Нидерландский (Голландский)"},
            new Language{Id = 54, Code =         "nor", Name = "Норвежский"},
            new Language{Id = 55, Code =         "pol", Name = "Польский"},
            new Language{Id = 56, Code =         "por", Name = "Португальский"},
            new Language{Id = 57, Code =         "kin", Name = "Руанда"},
            new Language{Id = 58, Code =         "ron", Name = "Румынский"},
            new Language{Id = 59, Code =         "rus", Name = "Русский"},
            new Language{Id = 60, Code =         "san", Name = "Санскрит"},
            new Language{Id = 61, Code =         "srp", Name = "Сербский"},
            new Language{Id = 62, Code =         "syr", Name = "Сирийский"},
            new Language{Id = 63, Code =         "slk", Name = "Словацкий"},
            new Language{Id = 64, Code =         "slv", Name = "Словенский"},
            new Language{Id = 65, Code =         "som", Name = "Сомали"},
            new Language{Id = 66, Code =         "swa", Name = "Суахили"},
            new Language{Id = 67, Code =         "tgk", Name = "Таджикский"},
            new Language{Id = 68, Code =         "tha", Name = "Тайский"},
            new Language{Id = 69, Code =         "tat", Name = "Татарский"},
            new Language{Id = 70, Code =         "bod", Name = "Тибетский"},
            new Language{Id = 71, Code =         "tur", Name = "Турецкий"},
            new Language{Id = 72, Code =         "tuk", Name = "Туркменский"},
            new Language{Id = 73, Code =         "uzb", Name = "Узбекский"},
            new Language{Id = 74, Code =         "ukr", Name = "Украинский"},
            new Language{Id = 75, Code =         "fij", Name = "Фиджи"},
            new Language{Id = 76, Code =         "fil", Name = "Филиппинский"},
            new Language{Id = 77, Code =         "phn", Name = "Финикийский"},
            new Language{Id = 78, Code =         "fin", Name = "Финский (Suomi)"},
            new Language{Id = 79, Code =         "fra", Name = "Французский", Weight = 100},
            new Language{Id = 80, Code =         "hin", Name = "Хинди"},
            new Language{Id = 81, Code =         "hrv", Name = "Хорватский"},
            new Language{Id = 82, Code =         "ces", Name = "Чешский"},
            new Language{Id = 83, Code =         "sco", Name = "Шотландский (англо-шотландский)"},
            new Language{Id = 84, Code =         "est", Name = "Эстонский"},
            new Language{Id = 85, Code =         "jav", Name = "Яванский"},
            new Language{Id = 86, Code =         "jpn", Name = "Японский", Weight = 80},
        };

        private static IEnumerable<LanguageLevel> LanguageLevels => new[]
        {
            new LanguageLevel{Id = 1, Code = "beginner", Name = "Начальный"},
            new LanguageLevel{Id = 2, Code = "elementary", Name = "Элементарный"},
            new LanguageLevel{Id = 3, Code = "pre-intermediate", Name = "Ниже среднего"},
            new LanguageLevel{Id = 4, Code = "intermediate", Name = "Средний"},
            new LanguageLevel{Id = 5, Code = "upper-intermediate", Name = "Выше среднего"},
            new LanguageLevel{Id = 6, Code = "advance", Name = "В совершенстве"},
        };

        private static IEnumerable<SocialNetwork> SocialNetworks => new[]
        {
            new SocialNetwork{Id = 1, Code = "facebook", Name = "Facebook", Icon = "facebook", IconColor = "#3b5998", Type = SocialNetworkType.SocialNetwork},
            new SocialNetwork{Id = 2, Code = "vk", Name = "ВКонтакте", Icon = "vk", IconColor = "#4a76a8", Type = SocialNetworkType.SocialNetwork},
            new SocialNetwork{Id = 3, Code = "ok", Name = "Одноклассники", Icon = "odnoklassniki", IconColor = "#ee8208", Type = SocialNetworkType.SocialNetwork},
            new SocialNetwork{Id = 4, Code = "twitter", Name = "Twitter", Icon = "twitter", IconColor = "#1da1f2", Type = SocialNetworkType.SocialNetwork},
            new SocialNetwork{Id = 5, Code = "instagram", Name = "Instagram", Icon = "instagram", IconColor = "#ff5241", Type = SocialNetworkType.SocialNetwork},
            new SocialNetwork{Id = 6, Code = "whatsapp", Name = "WhatsApp", Icon = "whatsapp", IconColor = "#00E676", Type = SocialNetworkType.Messenger},
            new SocialNetwork{Id = 7, Code = "viber", Name = "Viber", Icon = "viber", IconColor = "#574e92", Type = SocialNetworkType.Messenger},
            new SocialNetwork{Id = 8, Code = "skype", Name = "Skype", Icon = "skype", IconColor = "#00aff0", Type = SocialNetworkType.Messenger},
            new SocialNetwork{Id = 9, Code = "telegram", Name = "Telegram", Icon = "telegram", IconColor = "#29a7d9", Type = SocialNetworkType.Messenger},
            new SocialNetwork{Id = 10, Code = "youtube", Name = "YouTube", Icon = "youtube", IconColor = "#ff0000", Type = SocialNetworkType.SocialNetwork},
            new SocialNetwork{Id = 11, Code = "google-plus", Name = "Google+", Icon = "google-plus", IconColor = "#ce3525", Type = SocialNetworkType.SocialNetwork},
            new SocialNetwork{Id = 12, Code = "tumblr", Name = "Tumblr", Icon = "tumblr", IconColor = "#395976", Type = SocialNetworkType.SocialNetwork},
            new SocialNetwork{Id = 13, Code = "pinterest", Name = "Pinterest", Icon = "pinterest", IconColor = "#ee2d34", Type = SocialNetworkType.SocialNetwork},
        };

        private static IEnumerable<Country> Countries => new[]
        {
            new Country{Id =   1, Code = "895", AlphaCode2 = "AB", AlphaCode3 = "ABH", Name = "АБХАЗИЯ", FullName = "Республика Абхазия"},
            new Country{Id =   2, Code = "036", AlphaCode2 = "AU", AlphaCode3 = "AUS", Name = "АВСТРАЛИЯ"},
            new Country{Id =   3, Code = "040", AlphaCode2 = "AT", AlphaCode3 = "AUT", Name = "АВСТРИЯ", FullName = "Австрийская Республика"},
            new Country{Id =   4, Code = "031", AlphaCode2 = "AZ", AlphaCode3 = "AZE", Name = "АЗЕРБАЙДЖАН", FullName = "Республика Азербайджан"},
            new Country{Id =   5, Code = "008", AlphaCode2 = "AL", AlphaCode3 = "ALB", Name = "АЛБАНИЯ", FullName = "Республика Албания"},
            new Country{Id =   6, Code = "012", AlphaCode2 = "DZ", AlphaCode3 = "DZA", Name = "АЛЖИР", FullName = "Алжирская Народная Демократическая Республика"},
            new Country{Id =   7, Code = "016", AlphaCode2 = "AS", AlphaCode3 = "ASM", Name = "АМЕРИКАНСКОЕ САМОА"},
            new Country{Id =   8, Code = "660", AlphaCode2 = "AI", AlphaCode3 = "AIA", Name = "АНГИЛЬЯ"},
            new Country{Id =   9, Code = "024", AlphaCode2 = "AO", AlphaCode3 = "AGO", Name = "АНГОЛА", FullName = "Республика Ангола"},
            new Country{Id =  10, Code = "020", AlphaCode2 = "AD", AlphaCode3 = "AND", Name = "АНДОРРА", FullName = "Княжество Андорра"},
            new Country{Id =  11, Code = "010", AlphaCode2 = "AQ", AlphaCode3 = "ATA", Name = "АНТАРКТИДА"},
            new Country{Id =  12, Code = "028", AlphaCode2 = "AG", AlphaCode3 = "ATG", Name = "АНТИГУА И БАРБУДА"},
            new Country{Id =  13, Code = "032", AlphaCode2 = "AR", AlphaCode3 = "ARG", Name = "АРГЕНТИНА", FullName = "Аргентинская Республика"},
            new Country{Id =  14, Code = "051", AlphaCode2 = "AM", AlphaCode3 = "ARM", Name = "АРМЕНИЯ", FullName = "Республика Армения"},
            new Country{Id =  15, Code = "533", AlphaCode2 = "AW", AlphaCode3 = "ABW", Name = "АРУБА"},
            new Country{Id =  16, Code = "004", AlphaCode2 = "AF", AlphaCode3 = "AFG", Name = "АФГАНИСТАН", FullName = "Переходное Исламское Государство Афганистан"},
            new Country{Id =  17, Code = "044", AlphaCode2 = "BS", AlphaCode3 = "BHS", Name = "БАГАМЫ", FullName = "Содружество Багамы"},
            new Country{Id =  18, Code = "050", AlphaCode2 = "BD", AlphaCode3 = "BGD", Name = "БАНГЛАДЕШ", FullName = "Народная Республика Бангладеш"},
            new Country{Id =  19, Code = "052", AlphaCode2 = "BB", AlphaCode3 = "BRB", Name = "БАРБАДОС"},
            new Country{Id =  20, Code = "048", AlphaCode2 = "BH", AlphaCode3 = "BHR", Name = "БАХРЕЙН", FullName = "Королевство Бахрейн"},
            new Country{Id =  21, Code = "112", AlphaCode2 = "BY", AlphaCode3 = "BLR", Name = "БЕЛАРУСЬ", FullName = "Республика Беларусь"},
            new Country{Id =  22, Code = "084", AlphaCode2 = "BZ", AlphaCode3 = "BLZ", Name = "БЕЛИЗ"},
            new Country{Id =  23, Code = "056", AlphaCode2 = "BE", AlphaCode3 = "BEL", Name = "БЕЛЬГИЯ", FullName = "Королевство Бельгии"},
            new Country{Id =  24, Code = "204", AlphaCode2 = "BJ", AlphaCode3 = "BEN", Name = "БЕНИН", FullName = "Республика Бенин"},
            new Country{Id =  25, Code = "060", AlphaCode2 = "BM", AlphaCode3 = "BMU", Name = "БЕРМУДЫ"},
            new Country{Id =  26, Code = "100", AlphaCode2 = "BG", AlphaCode3 = "BGR", Name = "БОЛГАРИЯ", FullName = "Республика Болгария"},
            new Country{Id =  27, Code = "068", AlphaCode2 = "BO", AlphaCode3 = "BOL", Name = "БОЛИВИЯ, МНОГОНАЦИОНАЛЬНОЕ ГОСУДАРСТВО", FullName = "Многонациональное Государство Боливия"},
            new Country{Id =  28, Code = "535", AlphaCode2 = "BQ", AlphaCode3 = "BES", Name = "БОНЭЙР, СИНТ-ЭСТАТИУС И САБА"},
            new Country{Id =  29, Code = "070", AlphaCode2 = "BA", AlphaCode3 = "BIH", Name = "БОСНИЯ И ГЕРЦЕГОВИНА"},
            new Country{Id =  30, Code = "072", AlphaCode2 = "BW", AlphaCode3 = "BWA", Name = "БОТСВАНА", FullName = "Республика Ботсвана"},
            new Country{Id =  31, Code = "076", AlphaCode2 = "BR", AlphaCode3 = "BRA", Name = "БРАЗИЛИЯ", FullName = "Федеративная Республика Бразилия"},
            new Country{Id =  32, Code = "086", AlphaCode2 = "IO", AlphaCode3 = "IOT", Name = "БРИТАНСКАЯ ТЕРРИТОРИЯ В ИНДИЙСКОМ ОКЕАНЕ"},
            new Country{Id =  33, Code = "096", AlphaCode2 = "BN", AlphaCode3 = "BRN", Name = "БРУНЕЙ-ДАРУССАЛАМ"},
            new Country{Id =  34, Code = "854", AlphaCode2 = "BF", AlphaCode3 = "BFA", Name = "БУРКИНА-ФАСО"},
            new Country{Id =  35, Code = "108", AlphaCode2 = "BI", AlphaCode3 = "BDI", Name = "БУРУНДИ", FullName = "Республика Бурунди"},
            new Country{Id =  36, Code = "064", AlphaCode2 = "BT", AlphaCode3 = "BTN", Name = "БУТАН", FullName = "Королевство Бутан"},
            new Country{Id =  37, Code = "548", AlphaCode2 = "VU", AlphaCode3 = "VUT", Name = "ВАНУАТУ", FullName = "Республика Вануату"},
            new Country{Id =  38, Code = "348", AlphaCode2 = "HU", AlphaCode3 = "HUN", Name = "ВЕНГРИЯ"},
            new Country{Id =  39, Code = "862", AlphaCode2 = "VE", AlphaCode3 = "VEN", Name = "ВЕНЕСУЭЛА БОЛИВАРИАНСКАЯ РЕСПУБЛИКА", FullName = "Боливарианская Республика Венесуэла"},
            new Country{Id =  40, Code = "092", AlphaCode2 = "VG", AlphaCode3 = "VGB", Name = "ВИРГИНСКИЕ ОСТРОВА, БРИТАНСКИЕ", FullName = "Британские Виргинские острова"},
            new Country{Id =  41, Code = "850", AlphaCode2 = "VI", AlphaCode3 = "VIR", Name = "ВИРГИНСКИЕ ОСТРОВА, США", FullName = "Виргинские острова Соединенных Штатов"},
            new Country{Id =  42, Code = "704", AlphaCode2 = "VN", AlphaCode3 = "VNM", Name = "ВЬЕТНАМ", FullName = "Социалистическая Республика Вьетнам"},
            new Country{Id =  43, Code = "266", AlphaCode2 = "GA", AlphaCode3 = "GAB", Name = "ГАБОН", FullName = "Габонская Республика"},
            new Country{Id =  44, Code = "332", AlphaCode2 = "HT", AlphaCode3 = "HTI", Name = "ГАИТИ", FullName = "Республика Гаити"},
            new Country{Id =  45, Code = "328", AlphaCode2 = "GY", AlphaCode3 = "GUY", Name = "ГАЙАНА", FullName = "Республика Гайана"},
            new Country{Id =  46, Code = "270", AlphaCode2 = "GM", AlphaCode3 = "GMB", Name = "ГАМБИЯ", FullName = "Исламская Республика Гамбия"},
            new Country{Id =  47, Code = "288", AlphaCode2 = "GH", AlphaCode3 = "GHA", Name = "ГАНА", FullName = "Республика Гана"},
            new Country{Id =  48, Code = "312", AlphaCode2 = "GP", AlphaCode3 = "GLP", Name = "ГВАДЕЛУПА"},
            new Country{Id =  49, Code = "320", AlphaCode2 = "GT", AlphaCode3 = "GTM", Name = "ГВАТЕМАЛА", FullName = "Республика Гватемала"},
            new Country{Id =  50, Code = "324", AlphaCode2 = "GN", AlphaCode3 = "GIN", Name = "ГВИНЕЯ", FullName = "Гвинейская Республика"},
            new Country{Id =  51, Code = "624", AlphaCode2 = "GW", AlphaCode3 = "GNB", Name = "ГВИНЕЯ-БИСАУ", FullName = "Республика Гвинея-Бисау"},
            new Country{Id =  52, Code = "276", AlphaCode2 = "DE", AlphaCode3 = "DEU", Name = "ГЕРМАНИЯ", FullName = "Федеративная Республика Германия"},
            new Country{Id =  53, Code = "831", AlphaCode2 = "GG", AlphaCode3 = "GGY", Name = "ГЕРНСИ"},
            new Country{Id =  54, Code = "292", AlphaCode2 = "GI", AlphaCode3 = "GIB", Name = "ГИБРАЛТАР"},
            new Country{Id =  55, Code = "340", AlphaCode2 = "HN", AlphaCode3 = "HND", Name = "ГОНДУРАС", FullName = "Республика Гондурас"},
            new Country{Id =  56, Code = "344", AlphaCode2 = "HK", AlphaCode3 = "HKG", Name = "ГОНКОНГ", FullName = "Специальный административный регион Китая Гонконг"},
            new Country{Id =  57, Code = "308", AlphaCode2 = "GD", AlphaCode3 = "GRD", Name = "ГРЕНАДА"},
            new Country{Id =  58, Code = "304", AlphaCode2 = "GL", AlphaCode3 = "GRL", Name = "ГРЕНЛАНДИЯ"},
            new Country{Id =  59, Code = "300", AlphaCode2 = "GR", AlphaCode3 = "GRC", Name = "ГРЕЦИЯ", FullName = "Греческая Республика"},
            new Country{Id =  60, Code = "268", AlphaCode2 = "GE", AlphaCode3 = "GEO", Name = "ГРУЗИЯ"},
            new Country{Id =  61, Code = "316", AlphaCode2 = "GU", AlphaCode3 = "GUM", Name = "ГУАМ"},
            new Country{Id =  62, Code = "208", AlphaCode2 = "DK", AlphaCode3 = "DNK", Name = "ДАНИЯ", FullName = "Королевство Дания"},
            new Country{Id =  63, Code = "832", AlphaCode2 = "JE", AlphaCode3 = "JEY", Name = "ДЖЕРСИ"},
            new Country{Id =  64, Code = "262", AlphaCode2 = "DJ", AlphaCode3 = "DJI", Name = "ДЖИБУТИ", FullName = "Республика Джибути"},
            new Country{Id =  65, Code = "212", AlphaCode2 = "DM", AlphaCode3 = "DMA", Name = "ДОМИНИКА", FullName = "Содружество Доминики"},
            new Country{Id =  66, Code = "214", AlphaCode2 = "DO", AlphaCode3 = "DOM", Name = "ДОМИНИКАНСКАЯ РЕСПУБЛИКА"},
            new Country{Id =  67, Code = "818", AlphaCode2 = "EG", AlphaCode3 = "EGY", Name = "ЕГИПЕТ", FullName = "Арабская Республика Египет"},
            new Country{Id =  68, Code = "894", AlphaCode2 = "ZM", AlphaCode3 = "ZMB", Name = "ЗАМБИЯ", FullName = "Республика Замбия"},
            new Country{Id =  69, Code = "732", AlphaCode2 = "EH", AlphaCode3 = "ESH", Name = "ЗАПАДНАЯ САХАРА"},
            new Country{Id =  70, Code = "716", AlphaCode2 = "ZW", AlphaCode3 = "ZWE", Name = "ЗИМБАБВЕ", FullName = "Республика Зимбабве"},
            new Country{Id =  71, Code = "376", AlphaCode2 = "IL", AlphaCode3 = "ISR", Name = "ИЗРАИЛЬ", FullName = "Государство Израиль"},
            new Country{Id =  72, Code = "356", AlphaCode2 = "IN", AlphaCode3 = "IND", Name = "ИНДИЯ", FullName = "Республика Индия"},
            new Country{Id =  73, Code = "360", AlphaCode2 = "ID", AlphaCode3 = "IDN", Name = "ИНДОНЕЗИЯ", FullName = "Республика Индонезия"},
            new Country{Id =  74, Code = "400", AlphaCode2 = "JO", AlphaCode3 = "JOR", Name = "ИОРДАНИЯ", FullName = "Иорданское Хашимитское Королевство"},
            new Country{Id =  75, Code = "368", AlphaCode2 = "IQ", AlphaCode3 = "IRQ", Name = "ИРАК", FullName = "Республика Ирак"},
            new Country{Id =  76, Code = "364", AlphaCode2 = "IR", AlphaCode3 = "IRN", Name = "ИРАН, ИСЛАМСКАЯ РЕСПУБЛИКА", FullName = "Исламская Республика Иран"},
            new Country{Id =  77, Code = "372", AlphaCode2 = "IE", AlphaCode3 = "IRL", Name = "ИРЛАНДИЯ"},
            new Country{Id =  78, Code = "352", AlphaCode2 = "IS", AlphaCode3 = "ISL", Name = "ИСЛАНДИЯ", FullName = "Республика Исландия"},
            new Country{Id =  79, Code = "724", AlphaCode2 = "ES", AlphaCode3 = "ESP", Name = "ИСПАНИЯ", FullName = "Королевство Испания"},
            new Country{Id =  80, Code = "380", AlphaCode2 = "IT", AlphaCode3 = "ITA", Name = "ИТАЛИЯ", FullName = "Итальянская Республика"},
            new Country{Id =  81, Code = "887", AlphaCode2 = "YE", AlphaCode3 = "YEM", Name = "ЙЕМЕН", FullName = "Йеменская Республика"},
            new Country{Id =  82, Code = "132", AlphaCode2 = "CV", AlphaCode3 = "CPV", Name = "КАБО-ВЕРДЕ", FullName = "Республика Кабо-Верде"},
            new Country{Id =  83, Code = "398", AlphaCode2 = "KZ", AlphaCode3 = "KAZ", Name = "КАЗАХСТАН", FullName = "Республика Казахстан"},
            new Country{Id =  84, Code = "116", AlphaCode2 = "KH", AlphaCode3 = "KHM", Name = "КАМБОДЖА", FullName = "Королевство Камбоджа"},
            new Country{Id =  85, Code = "120", AlphaCode2 = "CM", AlphaCode3 = "CMR", Name = "КАМЕРУН", FullName = "Республика Камерун"},
            new Country{Id =  86, Code = "124", AlphaCode2 = "CA", AlphaCode3 = "CAN", Name = "КАНАДА"},
            new Country{Id =  87, Code = "634", AlphaCode2 = "QA", AlphaCode3 = "QAT", Name = "КАТАР", FullName = "Государство Катар"},
            new Country{Id =  88, Code = "404", AlphaCode2 = "KE", AlphaCode3 = "KEN", Name = "КЕНИЯ", FullName = "Республика Кения"},
            new Country{Id =  89, Code = "196", AlphaCode2 = "CY", AlphaCode3 = "CYP", Name = "КИПР", FullName = "Республика Кипр"},
            new Country{Id =  90, Code = "417", AlphaCode2 = "KG", AlphaCode3 = "KGZ", Name = "КИРГИЗИЯ", FullName = "Киргизская Республика"},
            new Country{Id =  91, Code = "296", AlphaCode2 = "KI", AlphaCode3 = "KIR", Name = "КИРИБАТИ", FullName = "Республика Кирибати"},
            new Country{Id =  92, Code = "156", AlphaCode2 = "CN", AlphaCode3 = "CHN", Name = "КИТАЙ", FullName = "Китайская Народная Республика"},
            new Country{Id =  93, Code = "166", AlphaCode2 = "CC", AlphaCode3 = "CCK", Name = "КОКОСОВЫЕ (КИЛИНГ) ОСТРОВА"},
            new Country{Id =  94, Code = "170", AlphaCode2 = "CO", AlphaCode3 = "COL", Name = "КОЛУМБИЯ", FullName = "Республика Колумбия"},
            new Country{Id =  95, Code = "174", AlphaCode2 = "KM", AlphaCode3 = "COM", Name = "КОМОРЫ", FullName = "Союз Коморы"},
            new Country{Id =  96, Code = "178", AlphaCode2 = "CG", AlphaCode3 = "COG", Name = "КОНГО", FullName = "Республика Конго"},
            new Country{Id =  97, Code = "180", AlphaCode2 = "CD", AlphaCode3 = "COD", Name = "КОНГО, ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА"},
            new Country{Id =  98, Code = "408", AlphaCode2 = "KP", AlphaCode3 = "PRK", Name = "КОРЕЯ, НАРОДНО-ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА", FullName = "Корейская Народно-Демократическая Республика"},
            new Country{Id =  99, Code = "410", AlphaCode2 = "KR", AlphaCode3 = "KOR", Name = "КОРЕЯ, РЕСПУБЛИКА", FullName = "Республика Корея"},
            new Country{Id = 100, Code = "188", AlphaCode2 = "CR", AlphaCode3 = "CRI", Name = "КОСТА-РИКА", FullName = "Республика Коста-Рика"},
            new Country{Id = 101, Code = "384", AlphaCode2 = "CI", AlphaCode3 = "CIV", Name = "КОТ Д’ИВУАР", FullName = "Республика Кот д’Ивуар"},
            new Country{Id = 102, Code = "192", AlphaCode2 = "CU", AlphaCode3 = "CUB", Name = "КУБА", FullName = "Республика Куба"},
            new Country{Id = 103, Code = "414", AlphaCode2 = "KW", AlphaCode3 = "KWT", Name = "КУВЕЙТ", FullName = "Государство Кувейт"},
            new Country{Id = 104, Code = "531", AlphaCode2 = "CW", AlphaCode3 = "CUW", Name = "КЮРАСАО"},
            new Country{Id = 105, Code = "418", AlphaCode2 = "LA", AlphaCode3 = "LAO", Name = "ЛАОССКАЯ НАРОДНО-ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА"},
            new Country{Id = 106, Code = "428", AlphaCode2 = "LV", AlphaCode3 = "LVA", Name = "ЛАТВИЯ", FullName = "Латвийская Республика"},
            new Country{Id = 107, Code = "426", AlphaCode2 = "LS", AlphaCode3 = "LSO", Name = "ЛЕСОТО", FullName = "Королевство Лесото"},
            new Country{Id = 108, Code = "430", AlphaCode2 = "LR", AlphaCode3 = "LBR", Name = "ЛИБЕРИЯ", FullName = "Республика Либерия"},
            new Country{Id = 109, Code = "422", AlphaCode2 = "LB", AlphaCode3 = "LBN", Name = "ЛИВАН", FullName = "Ливанская Республика"},
            new Country{Id = 110, Code = "434", AlphaCode2 = "LY", AlphaCode3 = "LBY", Name = "ЛИВИЯ", FullName = "Ливия"},
            new Country{Id = 111, Code = "440", AlphaCode2 = "LT", AlphaCode3 = "LTU", Name = "ЛИТВА", FullName = "Литовская Республика"},
            new Country{Id = 112, Code = "438", AlphaCode2 = "LI", AlphaCode3 = "LIE", Name = "ЛИХТЕНШТЕЙН", FullName = "Княжество Лихтенштейн"},
            new Country{Id = 113, Code = "442", AlphaCode2 = "LU", AlphaCode3 = "LUX", Name = "ЛЮКСЕМБУРГ", FullName = "Великое Герцогство Люксембург"},
            new Country{Id = 114, Code = "480", AlphaCode2 = "MU", AlphaCode3 = "MUS", Name = "МАВРИКИЙ", FullName = "Республика Маврикий"},
            new Country{Id = 115, Code = "478", AlphaCode2 = "MR", AlphaCode3 = "MRT", Name = "МАВРИТАНИЯ", FullName = "Исламская Республика Мавритания"},
            new Country{Id = 116, Code = "450", AlphaCode2 = "MG", AlphaCode3 = "MDG", Name = "МАДАГАСКАР", FullName = "Республика Мадагаскар"},
            new Country{Id = 117, Code = "175", AlphaCode2 = "YT", AlphaCode3 = "MYT", Name = "МАЙОТТА"},
            new Country{Id = 118, Code = "446", AlphaCode2 = "MO", AlphaCode3 = "MAC", Name = "МАКАО", FullName = "Специальный административный регион Китая Макао"},
            new Country{Id = 119, Code = "807", AlphaCode2 = "MK", AlphaCode3 = "MKD", Name = "РЕСПУБЛИКА МАКЕДОНИЯ[2]"},
            new Country{Id = 120, Code = "454", AlphaCode2 = "MW", AlphaCode3 = "MWI", Name = "МАЛАВИ", FullName = "Республика Малави"},
            new Country{Id = 121, Code = "458", AlphaCode2 = "MY", AlphaCode3 = "MYS", Name = "МАЛАЙЗИЯ"},
            new Country{Id = 122, Code = "466", AlphaCode2 = "ML", AlphaCode3 = "MLI", Name = "МАЛИ", FullName = "Республика Мали"},
            new Country{Id = 123, Code = "581", AlphaCode2 = "UM", AlphaCode3 = "UMI", Name = "МАЛЫЕ ТИХООКЕАНСКИЕ ОТДАЛЕННЫЕ ОСТРОВА СОЕДИНЕННЫХ ШТАТОВ"},
            new Country{Id = 124, Code = "462", AlphaCode2 = "MV", AlphaCode3 = "MDV", Name = "МАЛЬДИВЫ", FullName = "Мальдивская Республика"},
            new Country{Id = 125, Code = "470", AlphaCode2 = "MT", AlphaCode3 = "MLT", Name = "МАЛЬТА", FullName = "Республика Мальта"},
            new Country{Id = 126, Code = "504", AlphaCode2 = "MA", AlphaCode3 = "MAR", Name = "МАРОККО", FullName = "Королевство Марокко"},
            new Country{Id = 127, Code = "474", AlphaCode2 = "MQ", AlphaCode3 = "MTQ", Name = "МАРТИНИКА"},
            new Country{Id = 128, Code = "584", AlphaCode2 = "MH", AlphaCode3 = "MHL", Name = "МАРШАЛЛОВЫ ОСТРОВА", FullName = "Республика Маршалловы Острова"},
            new Country{Id = 129, Code = "484", AlphaCode2 = "MX", AlphaCode3 = "MEX", Name = "МЕКСИКА", FullName = "Мексиканские Соединенные Штаты"},
            new Country{Id = 130, Code = "583", AlphaCode2 = "FM", AlphaCode3 = "FSM", Name = "МИКРОНЕЗИЯ, ФЕДЕРАТИВНЫЕ ШТАТЫ", FullName = "Федеративные Штаты Микронезии"},
            new Country{Id = 131, Code = "508", AlphaCode2 = "MZ", AlphaCode3 = "MOZ", Name = "МОЗАМБИК", FullName = "Республика Мозамбик"},
            new Country{Id = 132, Code = "498", AlphaCode2 = "MD", AlphaCode3 = "MDA", Name = "МОЛДОВА, РЕСПУБЛИКА", FullName = "Республика Молдова"},
            new Country{Id = 133, Code = "492", AlphaCode2 = "MC", AlphaCode3 = "MCO", Name = "МОНАКО", FullName = "Княжество Монако"},
            new Country{Id = 134, Code = "496", AlphaCode2 = "MN", AlphaCode3 = "MNG", Name = "МОНГОЛИЯ"},
            new Country{Id = 135, Code = "500", AlphaCode2 = "MS", AlphaCode3 = "MSR", Name = "МОНТСЕРРАТ"},
            new Country{Id = 136, Code = "104", AlphaCode2 = "MM", AlphaCode3 = "MMR", Name = "МЬЯНМА", FullName = "Республика Союза Мьянма"},
            new Country{Id = 137, Code = "516", AlphaCode2 = "NA", AlphaCode3 = "NAM", Name = "НАМИБИЯ", FullName = "Республика Намибия"},
            new Country{Id = 138, Code = "520", AlphaCode2 = "NR", AlphaCode3 = "NRU", Name = "НАУРУ", FullName = "Республика Науру"},
            new Country{Id = 139, Code = "524", AlphaCode2 = "NP", AlphaCode3 = "NPL", Name = "НЕПАЛ", FullName = "Федеративная Демократическая Республика Непал"},
            new Country{Id = 140, Code = "562", AlphaCode2 = "NE", AlphaCode3 = "NER", Name = "НИГЕР", FullName = "Республика Нигер"},
            new Country{Id = 141, Code = "566", AlphaCode2 = "NG", AlphaCode3 = "NGA", Name = "НИГЕРИЯ", FullName = "Федеративная Республика Нигерия"},
            new Country{Id = 142, Code = "528", AlphaCode2 = "NL", AlphaCode3 = "NLD", Name = "НИДЕРЛАНДЫ", FullName = "Королевство Нидерландов"},
            new Country{Id = 143, Code = "558", AlphaCode2 = "NI", AlphaCode3 = "NIC", Name = "НИКАРАГУА", FullName = "Республика Никарагуа"},
            new Country{Id = 144, Code = "570", AlphaCode2 = "NU", AlphaCode3 = "NIU", Name = "НИУЭ", FullName = "Ниуэ"},
            new Country{Id = 145, Code = "554", AlphaCode2 = "NZ", AlphaCode3 = "NZL", Name = "НОВАЯ ЗЕЛАНДИЯ"},
            new Country{Id = 146, Code = "540", AlphaCode2 = "NC", AlphaCode3 = "NCL", Name = "НОВАЯ КАЛЕДОНИЯ"},
            new Country{Id = 147, Code = "578", AlphaCode2 = "NO", AlphaCode3 = "NOR", Name = "НОРВЕГИЯ", FullName = "Королевство Норвегия"},
            new Country{Id = 148, Code = "784", AlphaCode2 = "AE", AlphaCode3 = "ARE", Name = "ОБЪЕДИНЕННЫЕ АРАБСКИЕ ЭМИРАТЫ"},
            new Country{Id = 149, Code = "512", AlphaCode2 = "OM", AlphaCode3 = "OMN", Name = "ОМАН", FullName = "Султанат Оман"},
            new Country{Id = 150, Code = "136", AlphaCode2 = "KY", AlphaCode3 = "CYM", Name = "ОСТРОВА КАЙМАН"},
            new Country{Id = 151, Code = "184", AlphaCode2 = "CK", AlphaCode3 = "COK", Name = "ОСТРОВА КУКА"},
            new Country{Id = 152, Code = "796", AlphaCode2 = "TC", AlphaCode3 = "TCA", Name = "ОСТРОВА ТЕРКС И КАЙКОС"},
            new Country{Id = 153, Code = "074", AlphaCode2 = "BV", AlphaCode3 = "BVT", Name = "ОСТРОВ БУВЕ"},
            new Country{Id = 154, Code = "833", AlphaCode2 = "IM", AlphaCode3 = "IMN", Name = "ОСТРОВ МЭН"},
            new Country{Id = 155, Code = "574", AlphaCode2 = "NF", AlphaCode3 = "NFK", Name = "ОСТРОВ НОРФОЛК"},
            new Country{Id = 156, Code = "162", AlphaCode2 = "CX", AlphaCode3 = "CXR", Name = "ОСТРОВ РОЖДЕСТВА"},
            new Country{Id = 157, Code = "334", AlphaCode2 = "HM", AlphaCode3 = "HMD", Name = "ОСТРОВ ХЕРД И ОСТРОВА МАКДОНАЛЬД"},
            new Country{Id = 158, Code = "586", AlphaCode2 = "PK", AlphaCode3 = "PAK", Name = "ПАКИСТАН", FullName = "Исламская Республика Пакистан"},
            new Country{Id = 159, Code = "585", AlphaCode2 = "PW", AlphaCode3 = "PLW", Name = "ПАЛАУ", FullName = "Республика Палау"},
            new Country{Id = 160, Code = "275", AlphaCode2 = "PS", AlphaCode3 = "PSE", Name = "ПАЛЕСТИНА, ГОСУДАРСТВО", FullName = "Государство Палестина"},
            new Country{Id = 161, Code = "591", AlphaCode2 = "PA", AlphaCode3 = "PAN", Name = "ПАНАМА", FullName = "Республика Панама"},
            new Country{Id = 162, Code = "336", AlphaCode2 = "VA", AlphaCode3 = "VAT", Name = "ПАПСКИЙ ПРЕСТОЛ (ГОСУДАРСТВО — ГОРОД ВАТИКАН)"},
            new Country{Id = 163, Code = "598", AlphaCode2 = "PG", AlphaCode3 = "PNG", Name = "ПАПУА-НОВАЯ ГВИНЕЯ"},
            new Country{Id = 164, Code = "600", AlphaCode2 = "PY", AlphaCode3 = "PRY", Name = "ПАРАГВАЙ", FullName = "Республика Парагвай"},
            new Country{Id = 165, Code = "604", AlphaCode2 = "PE", AlphaCode3 = "PER", Name = "ПЕРУ", FullName = "Республика Перу"},
            new Country{Id = 166, Code = "612", AlphaCode2 = "PN", AlphaCode3 = "PCN", Name = "ПИТКЭРН"},
            new Country{Id = 167, Code = "616", AlphaCode2 = "PL", AlphaCode3 = "POL", Name = "ПОЛЬША", FullName = "Республика Польша"},
            new Country{Id = 168, Code = "620", AlphaCode2 = "PT", AlphaCode3 = "PRT", Name = "ПОРТУГАЛИЯ", FullName = "Португальская Республика"},
            new Country{Id = 169, Code = "630", AlphaCode2 = "PR", AlphaCode3 = "PRI", Name = "ПУЭРТО-РИКО"},
            new Country{Id = 170, Code = "638", AlphaCode2 = "RE", AlphaCode3 = "REU", Name = "РЕЮНЬОН"},
            new Country{Id = 171, Code = "643", AlphaCode2 = "RU", AlphaCode3 = "RUS", Name = "РОССИЯ", FullName = "Российская Федерация"},
            new Country{Id = 172, Code = "646", AlphaCode2 = "RW", AlphaCode3 = "RWA", Name = "РУАНДА", FullName = "Руандийская Республика"},
            new Country{Id = 173, Code = "642", AlphaCode2 = "RO", AlphaCode3 = "ROU", Name = "РУМЫНИЯ"},
            new Country{Id = 174, Code = "882", AlphaCode2 = "WS", AlphaCode3 = "WSM", Name = "САМОА", FullName = "Независимое Государство Самоа"},
            new Country{Id = 175, Code = "674", AlphaCode2 = "SM", AlphaCode3 = "SMR", Name = "САН-МАРИНО", FullName = "Республика Сан-Марино"},
            new Country{Id = 176, Code = "678", AlphaCode2 = "ST", AlphaCode3 = "STP", Name = "САН-ТОМЕ И ПРИНСИПИ", FullName = "Демократическая Республика Сан-Томе и Принсипи"},
            new Country{Id = 177, Code = "682", AlphaCode2 = "SA", AlphaCode3 = "SAU", Name = "САУДОВСКАЯ АРАВИЯ", FullName = "Королевство Саудовская Аравия"},
            new Country{Id = 178, Code = "748", AlphaCode2 = "SZ", AlphaCode3 = "SWZ", Name = "СВАЗИЛЕНД", FullName = "Королевство Свазиленд"},
            new Country{Id = 179, Code = "654", AlphaCode2 = "SH", AlphaCode3 = "SHN", Name = "СВЯТАЯ ЕЛЕНА, ОСТРОВ ВОЗНЕСЕНИЯ, ТРИСТАН-ДА-КУНЬЯ"},
            new Country{Id = 180, Code = "580", AlphaCode2 = "MP", AlphaCode3 = "MNP", Name = "СЕВЕРНЫЕ МАРИАНСКИЕ ОСТРОВА", FullName = "Содружество Северных Марианских островов"},
            new Country{Id = 181, Code = "690", AlphaCode2 = "SC", AlphaCode3 = "SYC", Name = "СЕЙШЕЛЫ", FullName = "Республика Сейшелы"},
            new Country{Id = 182, Code = "652", AlphaCode2 = "BL", AlphaCode3 = "BLM", Name = "СЕН-БАРТЕЛЕМИ"},
            new Country{Id = 183, Code = "663", AlphaCode2 = "MF", AlphaCode3 = "MAF", Name = "СЕН-МАРТЕН"},
            new Country{Id = 184, Code = "534", AlphaCode2 = "SX", AlphaCode3 = "SXM", Name = "СЕН-МАРТЕН (нидерландская часть)"},
            new Country{Id = 185, Code = "686", AlphaCode2 = "SN", AlphaCode3 = "SEN", Name = "СЕНЕГАЛ", FullName = "Республика Сенегал"},
            new Country{Id = 186, Code = "670", AlphaCode2 = "VC", AlphaCode3 = "VCT", Name = "СЕНТ-ВИНСЕНТ И ГРЕНАДИНЫ"},
            new Country{Id = 187, Code = "659", AlphaCode2 = "KN", AlphaCode3 = "KNA", Name = "СЕНТ-КИТС И НЕВИС"},
            new Country{Id = 188, Code = "662", AlphaCode2 = "LC", AlphaCode3 = "LCA", Name = "СЕНТ-ЛЮСИЯ"},
            new Country{Id = 189, Code = "666", AlphaCode2 = "PM", AlphaCode3 = "SPM", Name = "СЕН-ПЬЕР И МИКЕЛОН"},
            new Country{Id = 190, Code = "688", AlphaCode2 = "RS", AlphaCode3 = "SRB", Name = "СЕРБИЯ", FullName = "Республика Сербия"},
            new Country{Id = 191, Code = "702", AlphaCode2 = "SG", AlphaCode3 = "SGP", Name = "СИНГАПУР", FullName = "Республика Сингапур"},
            new Country{Id = 192, Code = "760", AlphaCode2 = "SY", AlphaCode3 = "SYR", Name = "СИРИЙСКАЯ АРАБСКАЯ РЕСПУБЛИКА"},
            new Country{Id = 193, Code = "703", AlphaCode2 = "SK", AlphaCode3 = "SVK", Name = "СЛОВАКИЯ", FullName = "Словацкая Республика"},
            new Country{Id = 194, Code = "705", AlphaCode2 = "SI", AlphaCode3 = "SVN", Name = "СЛОВЕНИЯ", FullName = "Республика Словения"},
            new Country{Id = 195, Code = "826", AlphaCode2 = "GB", AlphaCode3 = "GBR", Name = "СОЕДИНЕННОЕ КОРОЛЕВСТВО", FullName = "Соединенное Королевство Великобритании и Северной Ирландии"},
            new Country{Id = 196, Code = "840", AlphaCode2 = "US", AlphaCode3 = "USA", Name = "СОЕДИНЕННЫЕ ШТАТЫ", FullName = "Соединенные Штаты Америки"},
            new Country{Id = 197, Code = "090", AlphaCode2 = "SB", AlphaCode3 = "SLB", Name = "СОЛОМОНОВЫ ОСТРОВА"},
            new Country{Id = 198, Code = "706", AlphaCode2 = "SO", AlphaCode3 = "SOM", Name = "СОМАЛИ", FullName = "Федеративная Республика Сомали"},
            new Country{Id = 199, Code = "729", AlphaCode2 = "SD", AlphaCode3 = "SDN", Name = "СУДАН", FullName = "Республика Судан"},
            new Country{Id = 200, Code = "740", AlphaCode2 = "SR", AlphaCode3 = "SUR", Name = "СУРИНАМ", FullName = "Республика Суринам"},
            new Country{Id = 201, Code = "694", AlphaCode2 = "SL", AlphaCode3 = "SLE", Name = "СЬЕРРА-ЛЕОНЕ", FullName = "Республика Сьерра-Леоне"},
            new Country{Id = 202, Code = "762", AlphaCode2 = "TJ", AlphaCode3 = "TJK", Name = "ТАДЖИКИСТАН", FullName = "Республика Таджикистан"},
            new Country{Id = 203, Code = "764", AlphaCode2 = "TH", AlphaCode3 = "THA", Name = "ТАИЛАНД", FullName = "Королевство Таиланд"},
            new Country{Id = 204, Code = "158", AlphaCode2 = "TW", AlphaCode3 = "TWN", Name = "ТАЙВАНЬ (КИТАЙ)"},
            new Country{Id = 205, Code = "834", AlphaCode2 = "TZ", AlphaCode3 = "TZA", Name = "ТАНЗАНИЯ, ОБЪЕДИНЕННАЯ РЕСПУБЛИКА", FullName = "Объединенная Республика Танзания"},
            new Country{Id = 206, Code = "626", AlphaCode2 = "TL", AlphaCode3 = "TLS", Name = "ТИМОР-ЛЕСТЕ", FullName = "Демократическая Республика Тимор-Лесте"},
            new Country{Id = 207, Code = "768", AlphaCode2 = "TG", AlphaCode3 = "TGO", Name = "ТОГО", FullName = "Тоголезская Республика"},
            new Country{Id = 208, Code = "772", AlphaCode2 = "TK", AlphaCode3 = "TKL", Name = "ТОКЕЛАУ"},
            new Country{Id = 209, Code = "776", AlphaCode2 = "TO", AlphaCode3 = "TON", Name = "ТОНГА", FullName = "Королевство Тонга"},
            new Country{Id = 210, Code = "780", AlphaCode2 = "TT", AlphaCode3 = "TTO", Name = "ТРИНИДАД И ТОБАГО", FullName = "Республика Тринидад и Тобаго"},
            new Country{Id = 211, Code = "798", AlphaCode2 = "TV", AlphaCode3 = "TUV", Name = "ТУВАЛУ"},
            new Country{Id = 212, Code = "788", AlphaCode2 = "TN", AlphaCode3 = "TUN", Name = "ТУНИС", FullName = "Тунисская Республика"},
            new Country{Id = 213, Code = "795", AlphaCode2 = "TM", AlphaCode3 = "TKM", Name = "ТУРКМЕНИЯ", FullName = "Туркменистан"},
            new Country{Id = 214, Code = "792", AlphaCode2 = "TR", AlphaCode3 = "TUR", Name = "ТУРЦИЯ", FullName = "Турецкая Республика"},
            new Country{Id = 215, Code = "800", AlphaCode2 = "UG", AlphaCode3 = "UGA", Name = "УГАНДА", FullName = "Республика Уганда"},
            new Country{Id = 216, Code = "860", AlphaCode2 = "UZ", AlphaCode3 = "UZB", Name = "УЗБЕКИСТАН", FullName = "Республика Узбекистан"},
            new Country{Id = 217, Code = "804", AlphaCode2 = "UA", AlphaCode3 = "UKR", Name = "УКРАИНА"},
            new Country{Id = 218, Code = "876", AlphaCode2 = "WF", AlphaCode3 = "WLF", Name = "УОЛЛИС И ФУТУНА"},
            new Country{Id = 219, Code = "858", AlphaCode2 = "UY", AlphaCode3 = "URY", Name = "УРУГВАЙ", FullName = "Восточная Республика Уругвай"},
            new Country{Id = 220, Code = "234", AlphaCode2 = "FO", AlphaCode3 = "FRO", Name = "ФАРЕРСКИЕ ОСТРОВА"},
            new Country{Id = 221, Code = "242", AlphaCode2 = "FJ", AlphaCode3 = "FJI", Name = "ФИДЖИ", FullName = "Республика Фиджи"},
            new Country{Id = 222, Code = "608", AlphaCode2 = "PH", AlphaCode3 = "PHL", Name = "ФИЛИППИНЫ", FullName = "Республика Филиппины"},
            new Country{Id = 223, Code = "246", AlphaCode2 = "FI", AlphaCode3 = "FIN", Name = "ФИНЛЯНДИЯ", FullName = "Финляндская Республика"},
            new Country{Id = 224, Code = "238", AlphaCode2 = "FK", AlphaCode3 = "FLK", Name = "ФОЛКЛЕНДСКИЕ ОСТРОВА (МАЛЬВИНСКИЕ)"},
            new Country{Id = 225, Code = "250", AlphaCode2 = "FR", AlphaCode3 = "FRA", Name = "ФРАНЦИЯ", FullName = "Французская Республика"},
            new Country{Id = 226, Code = "254", AlphaCode2 = "GF", AlphaCode3 = "GUF", Name = "ФРАНЦУЗСКАЯ ГВИАНА"},
            new Country{Id = 227, Code = "258", AlphaCode2 = "PF", AlphaCode3 = "PYF", Name = "ФРАНЦУЗСКАЯ ПОЛИНЕЗИЯ"},
            new Country{Id = 228, Code = "260", AlphaCode2 = "TF", AlphaCode3 = "ATF", Name = "ФРАНЦУЗСКИЕ ЮЖНЫЕ ТЕРРИТОРИИ"},
            new Country{Id = 229, Code = "191", AlphaCode2 = "HR", AlphaCode3 = "HRV", Name = "ХОРВАТИЯ", FullName = "Республика Хорватия"},
            new Country{Id = 230, Code = "140", AlphaCode2 = "CF", AlphaCode3 = "CAF", Name = "ЦЕНТРАЛЬНО-АФРИКАНСКАЯ РЕСПУБЛИКА"},
            new Country{Id = 231, Code = "148", AlphaCode2 = "TD", AlphaCode3 = "TCD", Name = "ЧАД", FullName = "Республика Чад"},
            new Country{Id = 232, Code = "499", AlphaCode2 = "ME", AlphaCode3 = "MNE", Name = "ЧЕРНОГОРИЯ"},
            new Country{Id = 233, Code = "203", AlphaCode2 = "CZ", AlphaCode3 = "CZE", Name = "ЧЕХИЯ", FullName = "Чешская Республика"},
            new Country{Id = 234, Code = "152", AlphaCode2 = "CL", AlphaCode3 = "CHL", Name = "ЧИЛИ", FullName = "Республика Чили"},
            new Country{Id = 235, Code = "756", AlphaCode2 = "CH", AlphaCode3 = "CHE", Name = "ШВЕЙЦАРИЯ", FullName = "Швейцарская Конфедерация"},
            new Country{Id = 236, Code = "752", AlphaCode2 = "SE", AlphaCode3 = "SWE", Name = "ШВЕЦИЯ", FullName = "Королевство Швеция"},
            new Country{Id = 237, Code = "744", AlphaCode2 = "SJ", AlphaCode3 = "SJM", Name = "ШПИЦБЕРГЕН И ЯН МАЙЕН"},
            new Country{Id = 238, Code = "144", AlphaCode2 = "LK", AlphaCode3 = "LKA", Name = "ШРИ-ЛАНКА", FullName = "Демократическая Социалистическая Республика Шри-Ланка"},
            new Country{Id = 239, Code = "218", AlphaCode2 = "EC", AlphaCode3 = "ECU", Name = "ЭКВАДОР", FullName = "Республика Эквадор"},
            new Country{Id = 240, Code = "226", AlphaCode2 = "GQ", AlphaCode3 = "GNQ", Name = "ЭКВАТОРИАЛЬНАЯ ГВИНЕЯ", FullName = "Республика Экваториальная Гвинея"},
            new Country{Id = 241, Code = "248", AlphaCode2 = "AX", AlphaCode3 = "ALA", Name = "ЭЛАНДСКИЕ ОСТРОВА"},
            new Country{Id = 242, Code = "222", AlphaCode2 = "SV", AlphaCode3 = "SLV", Name = "ЭЛЬ-САЛЬВАДОР", FullName = "Республика Эль-Сальвадор"},
            new Country{Id = 243, Code = "232", AlphaCode2 = "ER", AlphaCode3 = "ERI", Name = "ЭРИТРЕЯ"},
            new Country{Id = 244, Code = "233", AlphaCode2 = "EE", AlphaCode3 = "EST", Name = "ЭСТОНИЯ", FullName = "Эстонская Республика"},
            new Country{Id = 245, Code = "231", AlphaCode2 = "ET", AlphaCode3 = "ETH", Name = "ЭФИОПИЯ", FullName = "Федеративная Демократическая Республика Эфиопия"},
            new Country{Id = 246, Code = "710", AlphaCode2 = "ZA", AlphaCode3 = "ZAF", Name = "ЮЖНАЯ АФРИКА", FullName = "Южно-Африканская Республика"},
            new Country{Id = 247, Code = "239", AlphaCode2 = "GS", AlphaCode3 = "SGS", Name = "ЮЖНАЯ ДЖОРДЖИЯ И ЮЖНЫЕ САНДВИЧЕВЫ ОСТРОВА"},
            new Country{Id = 248, Code = "896", AlphaCode2 = "OS", AlphaCode3 = "OST", Name = "ЮЖНАЯ ОСЕТИЯ", FullName = "Республика Южная Осетия"},
            new Country{Id = 249, Code = "728", AlphaCode2 = "SS", AlphaCode3 = "SSD", Name = "ЮЖНЫЙ СУДАН", FullName = "Республика Южный Судан"},
            new Country{Id = 250, Code = "388", AlphaCode2 = "JM", AlphaCode3 = "JAM", Name = "ЯМАЙКА"},
            new Country{Id = 251, Code = "392", AlphaCode2 = "JP", AlphaCode3 = "JPN", Name = "ЯПОНИЯ"},
        };
    }
}